export const FETCH_NEW_SALES = 'FETCH_NEW_SALES';
export const FETCH_MORE_SALES = 'FETCH_MORE_SALES';
export const FETCH_MORE_SALES_FROM_LAST = 'FETCH_MORE_SALES_FROM_LAST';
export const FETCH_CLEAR_SALES = 'FETCH_CLEAR_SALES';
