export const USER_SALE_ADDED = 'USER_SALE_ADDED';
export const USER_SALE_CHANGED = 'USER_SALE_CHANGED';
export const USER_SALE_DELETED = 'USER_SALE_DELETED';
export const USER_SALES_CLEAR = 'USER_SALES_CLEAR';
